"use client";
import React from "react";
import "./globals.css";
import Header from "./component/Header";
import Footer from "./component/Footer";
import { Geist, Geist_Mono } from "next/font/google";
// import type { Metadata } from "next";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "SandBrix",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
          <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Sora:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <div className="bg-[#180000]">
            <Header />
            <main>{children}</main>
            <Footer />
          </div>
      </body>
    </html>
  );
}
